item { 
	name:'yes'
	id:1
}
item { 
	name:'no'
	id:2
}
item { 
	name:'thank you'
	id:3
}
item { 
	name:'hello'
	id:4
}
item { 
	name:'A'
	id:5
}
item { 
	name:'B'
	id:6
}
item { 
	name:'C'
	id:7
}
item { 
	name:'D'
	id:8
}
item { 
	name:'E'
	id:9
}
item { 
	name:'F'
	id:10
}
item { 
	name:'G'
	id:11
}
item { 
	name:'H'
	id:12
}
item { 
	name:'I'
	id:13
}
item { 
	name:'J'
	id:14
}
item { 
	name:'K'
	id:15
}
item { 
	name:'L'
	id:16
}
item { 
	name:'M'
	id:17
}
item { 
	name:'N'
	id:18
}
item { 
	name:'O'
	id:19
}
item { 
	name:'P'
	id:20
}
item { 
	name:'Q'
	id:21
}
item { 
	name:'R'
	id:22
}
item { 
	name:'S'
	id:23
}
item { 
	name:'T'
	id:24
}
item { 
	name:'U'
	id:25
}
item { 
	name:'V'
	id:26
}
item { 
	name:'W'
	id:27
}
item { 
	name:'X'
	id:28
}
item { 
	name:'Y'
	id:29
}
item { 
	name:'Z'
	id:30
}
